services:
  - type: web
    name: primus-avia-strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: primus-avia-strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
      region: frankfurt
    envVars:
      - key: NODE_VERSION
        value: ~20.10.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: primus-avia-strapi-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: primus-avia-strapi-db
    plan: Free
    region: frankfurt
